### ISSUE TITLE
Password required for managed users - Integrated window authentication

### ISSUE THREAD

**Issue by ramsay2021** [Azure-Samples/ms-identity-java-desktop#19]
I am trying to run a sample code of MSAL Java Integrated window authentication and it throws an below exception,
ERROR com.microsoft.aad.msal4j.PublicClientApplication - [Correlation ID: 0b3328c3-0644-45bd-961c-09a45f9c851a] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Password is required for managed user
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.getAuthorizationGrantIntegrated(AcquireTokenByAuthorizationGrantSupplier.java:157)
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:50)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Exception in thread "main" java.util.concurrent.CompletionException: com.microsoft.aad.msal4j.MsalClientException: Password is required for managed user
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:89)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.microsoft.aad.msal4j.MsalClientException: Password is required for managed user
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.getAuthorizationGrantIntegrated(AcquireTokenByAuthorizationGrantSupplier.java:157)

AUTHORITY=https://login.microsoftonline.com/organizations/
SCOPE=user.read

I see this below comment in the sample code of Integrated window authentication,
"To acquire a IWA. You will need to generate a Kerberos ticket."

My Queries,
1) How to fix this issue "Password required for managed users" 
2) To generate a Kerberors ticket, i need to have principal username and password. How to create principal username and
set password?

Please help me to clarify this doubts.

Thanks,
Ram

**Comment by Avery-Dunn** [comment]
I think this question was answered in your similar question in the library's main repo: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/480

Closing this this thread, feel free to re-open and leave a comment if there are still any related issues.
